// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "", // your region here
    "aws_cognito_region": "", // your region here
    "aws_user_pools_id": "", // your user pool ID here
    "aws_user_pools_web_client_id": "", // your user pool web client id here
    "oauth": {},
};

export default awsmobile;
